spring:
    data:
        arangodb:
            database: beorgdb
            hosts: 127.0.0.1:8529
            password: 123456
            user: root
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    batch:
        job:
            enabled: false

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 5MB
            max-request-size: 215MB

    http:
        multipart:
            enabled: true
file:
    upload-dir: /Users/hp/uploads